/********************************************************************************
* MICROCHIP PM8596 EXPLORER FIRMWARE
*                                                                               
* Copyright (c) 2018, 2019 Microchip Technology Inc. All rights reserved. 
*                                                                               
* Licensed under the Apache License, Version 2.0 (the "License"); you may not 
* use this file except in compliance with the License. You may obtain a copy of 
* the License at http://www.apache.org/licenses/LICENSE-2.0
*                                                                               
* Unless required by applicable law or agreed to in writing, software 
* distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
* WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
* License for the specific language governing permissions and limitations under 
* the License.
********************************************************************************/

/********************************************************************************
*   DESCRIPTION :
*     This file contains firmware definitions used to profile base
*     code - base code is common to all projects.  Each platform has
*     their own copy of pmc_profile.h; the list of #define
*     switches will be the same from project to project, however the
*     actual value for each #define definition may differ from project
*     to project.
*
*     #define definitions in this file should have a value of 0 or 1.
*     Value 0 -> disable STATS or DEBUG
*     Value 1 -> enable STATS or DEBUG
*
*     Code should use #if (MY_STATS_DEBUG_SWITCH == 1) to enable
*     stats or debug code.
*
*     This approach is desirable instead of using #ifdef.  This style
*     detects header file inclusion issues; using #if will cause the
*     compiler to warn whenever a reference to MY_STATS_DEBUG_SWITCH is
*     found without inclusion of pmc_profile_base.h.  In particular, this
*     helps to debug sophisticated use cases when the #define is used in
*     another header but the inclusion of these header files is incorrect,
*     which cause non-intended behavior.
*
*   NOTES       :
*******************************************************************************/



/*---- Compile Options -----------------------------------------------------*/
#ifndef _PMC_PROFILE_H
#define _PMC_PROFILE_H

/*
** Include files
*/

/******************************************************************************
**
**
** The following #defines can safely be switched on or off without side effects.
**
**
******************************************************************************/

/*
** Module stats collection control
*/

/* stats collection on AAP2 */
#define RMWIO_STATS_ON          0
#define ERAAE_STATS_ON          0

/*
** Module debug/sanity check control
*/

/******************************************************************************
**
**
** The following #defines CAN NOT be safely switched on or off without side
** effects. Changing these is NOT RECOMMENDED.
**
**
******************************************************************************/

/*
** Debugging interrupt counts
*/
#define CICINT_DEBUG                    0


/*
** Definitions to allow function tracing
*/
#define TRACE_PEM                       0

#define USE_SDS_EMULATION               1

/*
** RAIDGen Mode
** RAIDGEN_DISABLED: RAIDGen is disabled (default)
** RAIDGEN_STAND_ALONE: Legacy RAIDGen without SmartArray integration
** RAIDGEN_SMART_ARRAY: SmartArray integrated RAIDGen
*/
#define RAIDGEN_MODE                    RAIDGEN_STAND_ALONE
#define RAIDGEN_DISABLED                0
#define RAIDGEN_STAND_ALONE             1
#define RAIDGEN_SMART_ARRAY             2

/* Check RAIDGen compile flag is valid */
#if (RAIDGEN_MODE != RAIDGEN_DISABLED) && \
    (RAIDGEN_MODE != RAIDGEN_STAND_ALONE) && \
    (RAIDGEN_MODE != RAIDGEN_SMART_ARRAY)
#error RAIDGEN_MODE compile flag is not set to a valid value
#endif

/*
** RMWIO_SEPARATE_COMP_EVENT_QUEUE Value
**
** 0: Send RMWIO events and completions on the RMWIO message queue.  The RMWIO
**    event queue is unused.  Use this option if the traffic generation
**    application can process these messages at the same priority.  The events
**    and completions will be interleaved in the order in which they are
**    generated by RMWIO.
**
** 1: Send RMWIO completions on the RMWIO message queue, and RMWIO events on
**    the RMWIO event queue.  Use this option if the traffic generation
**    application needs to process events at higher priority than completions.
**    In order for this model to work, the completions must be processed in
**    thread context.  Events can be processed either in ISR context, or in a
**    higher priority thread.
*/
#define RMWIO_SEPARATE_COMP_EVENT_QUEUE 1

/*
** The following #define is meant for a Protium build with eRAAE, OSSP 0, and SM0.
*/
#define PMC_SM0_ONLY               0

/*
** Use the following to enable/disable support for an internal virtual SES device.
** When enabled a virtual SES device is reported to the RAID Stack by RMW.
** Commands directed at a Virtual SES are forwarded to the SVPD module.
** Disabled by default for all SmartArray products. May be enabled for OEM RAID stack
** ports that require an internal virtual SES port.
*/
#define VIRTUAL_SES_SUPPORT        FALSE

/*
** Use for PE firmware builds. PE build should always be built with EXPLORER_BRINGUP = 1
*/
#define EXPLORER_PE_BUILD    0

/*
** Use for Explorer bringup when there is no host to send commands down the OpenCAPI
** interface.
*/
#define EXPLORER_BRINGUP     0

/*
** Compile assert if PE BUILD is enabled EXPLORER_BRINGUP flag must also be set.
*/
#if (EXPLORER_PE_BUILD == 1 && EXPLORER_BRINGUP == 0)
#error "EXPLORER_BRINGUP must be set to 1 if EXPLORER_PE_BUILD=1."
#endif

#endif /* _PMC_PROFILE_H */





